### ISSUE TITLE
Problem to remove active users command

### ISSUE THREAD

**Issue by jeanpablojp** [GideonLeGrange/mikrotik-java#10]
I'm trying to remove active users from hotspot but its not working.
I've tried this commands:

(I need to remove all the active users from hotspot where the field user="teste")

This works on mikrotik:
/ip hotspot active remove [find user="teste"]

Using the API i've tried:
/ip/hotspot/active/remove [find user='teste']
/ip/hotspot/active/remove user='teste'
/ip/hotspot/active/remove [find user=\"teste\"]
/ip/hotspot/active/remove user=\"teste\"

There is a bug or limitation here or i'm doing something wrong here???

Thanks in advance.

**Comment by Syleri** [comment]
I am little confused here. To me neither of this is working:
Example that should work:

con.execute("/ip/hotspot/user/remove .id=joe")

Example that will work:

Example:

        List<Map<String, String>> res = con.execute("/ip/hotspot/active/print where name=teste");
        for (Map<String, String> attr : res) {
            String id = attr.get(".id");
            con.execute("/ip/hotspot/active/remove .id=" + id);
        }
    }

**Comment by Syleri** [comment]
I found what my problem was instead of "/ip/hotspot/active/print where name=teste", you must have 
                                                               "/ip/hotspot/active/print where user=teste"
Thanks!
