### ISSUE TITLE
Can't exec  cmd1 [cmd2] and cmd param(no name)

### ISSUE THREAD

**Issue by pkptzx** [GideonLeGrange/mikrotik-java#20]
Can't exec  cmd1 [cmd2] and cmd param(no name)
like:
/ip/hotspot/active/remove [/ip/hotspot/active/print where mac-address="00:xx:CC:xx:xx:xx"]

and
/ip/hotspot/active/remove 0
/ip/hotspot/active/remove *F90410AC
*F90410AC is exec /ip/hotspot/active/print where mac-address="00:xx:CC:xx:xx:xx" command's .id

help~please~

**Comment by GideonLeGrange** [comment]
Hello

Can you please give me the following information:
1. The version of the API you are using
2. The error you receive when trying to execute the command. The exception stack trace will be helpful. 

Gideon

**Comment by pkptzx** [comment]
I want use api execute script:
/ip hotspot active remove [/ip hotspot active find mac-address="00:xx:CC:xx:76:xx"]

but , i don't konw how to change script to api~

RouterOS VERSION:6.2.7
LEVEL 6L

[sorry,my English is very poor ^_^]

**Comment by GideonLeGrange** [comment]
Can you show me an example of your code? It is not clear to me if you are actually trying to use my Java API. If you are trying to use the API, can you please show me a stack trace of the error?

**Comment by GideonLeGrange** [comment]
Not enough information to assist further.
