### ISSUE TITLE
Adding User and getting exception.

### ISSUE THREAD

**Issue by Syleri** [GideonLeGrange/mikrotik-java#22]
Hello I am using the following code to add user from java:
`con.execute("/ip/hotspot/user/add name="+username+" password="+password);`
And I am getting the following exception:
`mikrotik.MikrotikApiException: unknown parameter
	at mikrotik.impl.ApiConnectionImpl$SyncListener.getResults(ApiConnectionImpl.java:511)
	at mikrotik.impl.ApiConnectionImpl$SyncListener.access$1(ApiConnectionImpl.java:500)
	at mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:146)
	at mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:113)
        at mikrotik.Disconnect.addUser(Disconnect.java:110) <-- This is the above line of code.
.......
`
I have syntax error? Or I missing something else?

Thanks for your attention and time.

**Comment by GideonLeGrange** [comment]
This works for me. Is suspect the problem is with the contents of your username or password variable. 

Gideon

**Comment by Syleri** [comment]
Thanks for your response, but can you be more specific by the meaning of "contents" of username and password? The username and password are inserted to the mikrotik by the way.

**Comment by GideonLeGrange** [comment]
Hello 

What is username and password set to when you do the API call? 

You define username and password elsewhere and then make the command by doing: 

"/ip/hotspot/user/add name="+username+" password="+password

So if username or password is for example empty, that will evaluate to something similar to

"/ip/hotspot/user/add name= password=somepassword"

or  

"/ip/hotspot/user/add name=someuser password="

Either way, the command you generate will not be a valid Mikrotik API command. 


I suggest you put a debug println before the API call. Do something like:

String command = "/ip/hotspot/user/add name="+username+" password=“+password;
System.out.println(“DEBUG: command=“ + command);
con.execute(command);

Hope this helps! 
Gideon

**Comment by Syleri** [comment]
Thanks for your response, it help a lot actually. :)
