### ISSUE TITLE
Grammar invalid

### ISSUE THREAD

**Issue by jeanpablojp** [GideonLeGrange/mikrotik-java#24]
Im trying to use the following commands bellow but i'm getting a grammar error:
/ip/dhcp-server/lease/print where comment ~'#Router#'
/ip/dhcp-server/lease/print where comment ~'^#Router#'

(The first command lists registers that contains the string "#Router#" inside the comments and the second the registers that starts with this string.)

It works OK in winbox:
/ip dhcp-server lease print where comment ~"#Router#"
/ip dhcp-server lease print where comment ~"^#Router#"

Is it an API limitation or a bug???

Thanks.

**Comment by GideonLeGrange** [comment]
Hello

Short reply: API limitation. 

Long story: 

According to the Mikrotik documentation, it looks like the ~ operator is not supported by the API. I therefore don't parse it in the library, and you will get an exception on those where commands. The documentation is here: http://wiki.mikrotik.com/wiki/Manual:API If you want to know more about it, look at the "Queries" section - there's simply no query that I can use for a contains operation.

I did play with it to see if it was unimplemented or just undocumented, but it's worse:  If I try to do a ~ query, RouterOS accepts the command (does not return an error) but does not apply it. 

Kind regards
Gideon
