### ISSUE TITLE
Force close in android on connect

### ISSUE THREAD

**Issue by oclouds** [GideonLeGrange/mikrotik-java#25]
I'm trying to use mikrotik api Java in android, but when i downloaded it and added it in android studio project and used it the app forced to close!

imports in the begging of the MainActivity:
`
import me.legrange.mikrotik.MikrotikApiException;
import me.legrange.mikrotik.ApiConnection;
import me.legrange.mikrotik.ResultListener;
`
my java code to **Connect**:
`
ApiConnection con = ApiConnection.connect("10.0.1.1");
`
This is My Files: http://i.stack.imgur.com/3XYlk.png

thanks.

**Comment by GideonLeGrange** [comment]
This is not a library issue. If importing a jar and adding it to Android Studio causes it to close, that's a Android Studio, and I suggest you ask for help on the Android Studio forums. 

Gideon
