### ISSUE TITLE
Android Application has stopped

### ISSUE THREAD

**Issue by AmrSubZero** [GideonLeGrange/mikrotik-java#31]
##### Developing an android application testing the connection to the RouterOS using this API

Added the Maven compile code to the build.gradle in my android app :

```sh
compile 'me.legrange:mikrotik:2.2'
```

Imported the Class of the API :

```sh
import me.legrange.mikrotik.ApiConnection;
import me.legrange.mikrotik.MikrotikApiException;
```

And here's my code in the MainActivity :

```sh
public class MainActivity extends ActionBarActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        try {
            ApiConnection.connect("192.168.1.2");
        } catch (MikrotikApiException e) {
            e.printStackTrace();
        }
    }
}
```

##### As we see it's very simple, nothing complicated just trying to connect

The problem is when i test the app it's crashing and saying
> Unfortunetly App has stopped

##### Note : I'm asking for internet access permession in the installation process

I assume i'm using the API the right way, so how to fix this problem?

**Comment by Metori** [comment]
After "Unfortunetely App has stopped" you will receive stack trace in LogCat. Did you read it?

**Comment by GideonLeGrange** [comment]
@AmrSubZero You seem to be instantiating the app correctly. I will need to see a stack trace to understand the problem. Can you get a stack trace?

**Comment by GideonLeGrange** [comment]
@AmrSubZero

Having thought about this some more, I speculate that the code is causing a `Throwable` or `RuntimeException`. I see you have a catch there with a `printStackTrace()`, so assuming you can get the output of a print, I suggest you change your code like this:

```java
public class MainActivity extends ActionBarActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        try {
            ApiConnection.connect("192.168.1.2");
        } catch (MikrotikApiException e) {
            e.printStackTrace();
        }
        catch (Throwable e) {
            e.printStackTrace();
        }
    }
}
```

At least we'll then be able to pick up why the app is stopping. Please let me know, or if this issue is no longer relevant, please close the issue.
