### ISSUE TITLE
Error when parameter has space in it

### ISSUE THREAD

**Issue by dgreat91** [GideonLeGrange/mikrotik-java#33]
Hi Gideon, 

When i run command "/interface/bridge/port/print where interface=Public Area", I receive the error "me.legrange.mikrotik.impl.ParseException: Expected [EOL] but found TEXT at position 56" which falls at the space position. I read through issue #3 which seems to report the exact same problem but no solution there that i can understand.

**Comment by GideonLeGrange** [comment]
Hi 

Have you tried to quote the text containing the space? For example try:

`"/interface/bridge/port/print where interface=\"Public Area\""`

Let me know if that solves it for you, if it does I probably need to document this publicly!

**Comment by GideonLeGrange** [comment]
No response. Assume it works.

**Comment by GideonLeGrange** [comment]
Confirmed that quoting the text with the space in work.

**Comment by dgreat91** [comment]
Hi very sorry. I havent tested because i was away on system installment. It
works. Thanks very much. Your assistance is really appreciated.

On Wednesday, February 3, 2016, Gideon le Grange <notifications@github.com>
wrote:

> Confirmed that quoting the text with the space in work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GideonLeGrange/mikrotik-java/issues/33#issuecomment-178797210>
> .
>


-- 

Tukur Anas Mohammad
+601123765837
