### ISSUE TITLE
The new stacktrace is quite annoying

### ISSUE THREAD

**Issue by OlivierBoucher** [GideonLeGrange/mikrotik-java#34]
Each time we close a connection we now get this stacktrace printed out due to interruptedException.

Please refer to this method  of ApiConnectionImpl.Reader

```java
@Override
        public void run() {
            while (connected) {
                try {
                    String s = Util.decode(in);
                    if (s != null) {
                        queue.put(s);
                    }
                } catch (ApiDataException ex) {
                    try {
                        queue.put(ex);
                    } catch (InterruptedException ex2) {
                    }
                } catch (ApiConnectionException | InterruptedException ex) {
                    ex.printStackTrace(); // HERE
                }
            }
        }
```

This was not present in 2.2. I don't really know what should be done to identify that it comes from a disconnect's interrupt. If you have any idea just let me know and I'll submit a PR

**Comment by GideonLeGrange** [comment]
Hi @OlivierBoucher 

I saw this too and find that it is reproducible, but isn't 100% reliable (it doesn't always occur on my equipment). While the stack trace is harmless, the behaviour of catching the exception and just printing isn't great. I'll look into a solution for this and update this issue. 

Gideon

**Comment by GideonLeGrange** [comment]
Hi @OlivierBoucher 

I've changed code to suppress the stack trace while improving the error handling in a case where there is a real socket error while processing data.

Can you please test against master branch and see if it gives you better results?

**Comment by OlivierBoucher** [comment]
Thanks @GideonLeGrange, will test this weekend.
