### ISSUE TITLE
Connection by ssh

### ISSUE THREAD

**Issue by tesodara** [GideonLeGrange/mikrotik-java#35]
Dear Sir,

Can you give me a way to remote Mikrotik router by SSH ? 

Thank you

**Comment by GideonLeGrange** [comment]
I recommend you check out and ask your question here: http://forum.mikrotik.com/

**Comment by tesodara** [comment]
Thank you, but I mean to connect by your API.

**Comment by GideonLeGrange** [comment]
I'm not sure what you are asking. If are asking how to use the API to setup SSH, I don't know how. You need to find the RouterOS command line commands and translate them to API syntax. If you're asking to use the API over SSH, it doesn't work that way, it uses the RouterOS API protocol. 

The README should be enough to get you going.
