### ISSUE TITLE
Unknown Parameter for command "/put message=[resolve www.facebook.com]"

### ISSUE THREAD

**Issue by dgreat91** [GideonLeGrange/mikrotik-java#36]
Hi;

"/put message=[resolve www.facebook.com]"

While trying to run the above command, i keep getting the error me.legrange.mikrotik.MikrotikApiException: unknown parameter. Please is this a known behavior and is  there a work around? Or is my command wrong??

This command works when tested through CMD

**Comment by GideonLeGrange** [comment]
Not all command line commands will work through the API. This is due to limitations in the underlying RouterOS API, not this library. 

However, I don't understand what you're trying to do here. Generating a message from a script works on the console, but it does not make sense in the API.
