### ISSUE TITLE
How to add and modify IP -> Pool

### ISSUE THREAD

**Issue by rudiw** [GideonLeGrange/mikrotik-java#41]
Hi..

How to add and modify IP Pool with values:

1. name
2. addresses

I have tried like this:
```
@Test
public void addIpPool() throws MikrotikApiException {
	final MikroTikIPPool upIpPool = new MikroTikIPPool();
	upIpPool.setAddresses("192.168.12.10-192.168.12.254");
	upIpPool.setName("ipp_ri1");
	
	final List<Map<String, String>> result = conn.
			execute(String.format("/ip/pool/add name=\"%s\" addresses=\"%s\"",
					upIpPool.getName(), upIpPool.getAddresses()));
}
```

It is not works..

**Comment by GideonLeGrange** [comment]
Do you receive an error message? If so, can you please show me the stack trace? 

Gideon

**Comment by GideonLeGrange** [comment]
Your command is wrong: `addresses` is not a parameter for `/ip/pool/add`, the correct parameter is `ranges`. 

Command line example: 
`
/ip pool add name="pool1" ranges="10.0.0.1-10.0.0.254"`
`

API example:

`
 final List<Map<String, String>> result = con.
            execute(String.format("/ip/pool/add name=\"%s\" ranges=\"%s\"",
                    "pool21, "10.0.0.1-10.0.0.254"));
`

**Comment by rudiw** [comment]
Thanks @GideonLeGrange, I will try soon..
