### ISSUE TITLE
/file/print command timeout

### ISSUE THREAD

**Issue by dgreat91** [GideonLeGrange/mikrotik-java#43]
When i try to run the command  "/file/print" the connection returns nothing until timeout. I increased the timeout but still the same. Please is there anyway around this? Thanks

**Comment by GideonLeGrange** [comment]
This was previously working as per `examples/DownloadConfig.java` in the source. It's no longer working and I don't know why. 

I'll investigate it and update this issue when I know more.

**Comment by GideonLeGrange** [comment]
I merged a pull request from another contributor that addressed this issue, and `examples/DownloadConfig.java` now works. If you want to test, check out the `master` and try that. I'll release 3.0.2 by the weekend.

**Comment by dgreat91** [comment]
Thank you
