### ISSUE TITLE
problems reading user profile in hotspot

### ISSUE THREAD

**Issue by azulxp** [GideonLeGrange/mikrotik-java#44]
hello I have problems reading user profile in hotspot
my code:

```
public ArrayList<Perfil> obtenerListaPerfiles() throws MikrotikApiException{
		String cmd= "/ip/hotspot/user/profile/getall";
		List<Map<String, String>> rs = con.execute(cmd);
		ArrayList<Perfil> perfiles= new ArrayList<Perfil>();
		for (Map<String,String> r : rs) {
			 perfiles.add(
				 new Perfil(
					 "",
					 r.get("name"),
					 r.get("session-timeout"),
					 r.get("rate-limit")
				 )
			 );
		}
		System.out.println(cmd);
		return perfiles;
	}
```
the problem occurs when I put a script in some user profile

![profile](https://cloud.githubusercontent.com/assets/22648891/19135614/9baaced8-8b2b-11e6-9fee-0b799f743951.png)

* When off the script code works.

**Comment by GideonLeGrange** [comment]
What happens? Does the API raise an exception, and if so, can you share the stack trace, or do you not get the result you want? What is the error?

**Comment by azulxp** [comment]
this is the error

`Error: Command timed out after 60000 ms`

**Comment by GideonLeGrange** [comment]
Is this the script (it's hard to make out from the screen shot)?

```
{ 
	local date [ /system clock get date ]
        if ([ /ip hotspot user get $user comment ] = “”) do = { 
           [ /ip hotspot user set $user comment=$date ]
        }
}
```

If this is not correct, can you send me the script please? 

With the above script I have no error at all. Here is my test code:

```java 

    private void test() throws MikrotikApiException {
        String cmd= "/ip/hotspot/user/profile/getall";
        List<Map<String, String>> rs = con.execute(cmd);
        for (Map<String,String> r : rs) {
            System.out.println(r);
        }
    }
```

And the result it produces is: 


```
tag=3, data={add-mac-cookie=true, default=true, keepalive-timeout=2m, status-autorefresh=1m, name=default, transparent-proxy=false, .id=*0, shared-users=1, idle-timeout=none, address-list=, mac-cookie-timeout=3d}
tag=3, data={add-mac-cookie=true, keepalive-timeout=2m, status-autorefresh=1m, on-login={ 
    local date [ /system clock get date ]
        if ([ /ip hotspot user get $user comment ] = ) do = { 
           [ /ip hotspot user set $user comment=$date ]
        }
} , name=test, transparent-proxy=false, .id=*1, shared-users=1, idle-timeout=none, address-list=, mac-cookie-timeout=3d}
```

**Comment by azulxp** [comment]
use your test code

` private void test() throws MikrotikApiException {
        String cmd= "/ip/hotspot/user/profile/getall";
        List<Map<String, String>> rs = con.execute(cmd);
        for (Map<String,String> r : rs) {
            System.out.println(r);
        }
    }`

now sends this error

`Exception in thread "main" me.legrange.mikrotik.MikrotikApiException: Command timed out after 5000 ms
	at me.legrange.mikrotik.impl.ApiConnectionImpl$SyncListener.getResults(ApiConnectionImpl.java:471)
	at me.legrange.mikrotik.impl.ApiConnectionImpl$SyncListener.access$100(ApiConnectionImpl.java:425)
	at me.legrange.mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:110)
	at me.legrange.mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:68)
	at pruebas.Main.main(Main.java:32)
Caused by: me.legrange.mikrotik.ApiConnectionException: Command timed out after 5000 ms
	at me.legrange.mikrotik.impl.ApiConnectionImpl$SyncListener.getResults(ApiConnectionImpl.java:463)
	... 4 more`

the problem is only with that query.

the script of the user profile is correct

**Comment by GideonLeGrange** [comment]
Let's try some things: 
- Can you please make sure you're using the latest version of mikrotik-java, 3.0.2 (available [https://github.com/GideonLeGrange/mikrotik-java/releases/tag/v3.0.2](here).
- Can you tell me which RouterOS version you're using? I'm running 6.34.6

**Comment by GideonLeGrange** [comment]
Please try v3.0.2 as per above. it contains pull request #37 which I think is the fix for your problem.

**Comment by azulxp** [comment]
thanks to the version 3.0.2 the problem was corrected.
