### ISSUE TITLE
Error with where and operator <

### ISSUE THREAD

**Issue by herlon2015** [GideonLeGrange/mikrotik-java#46]
List<Map<String,String>> rs = router.execute("/ipv6 / dhcp-server / binding / print detail where prefix-pool=PoolPD last-seen<6m");

me.legrange.mikrotik.impl.ParseException: Expected [EOL] but found TEXT at position 80
	at me.legrange.mikrotik.impl.Parser.expect(Parser.java:183)
	at me.legrange.mikrotik.impl.Parser.parse(Parser.java:32)
	at me.legrange.mikrotik.impl.Parser.parse(Parser.java:17)
	at me.legrange.mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:68)

The functionality for operator use has not yet been implemented in the API or is a command writing error.
If it is a writing error how should I do it?

**Comment by GideonLeGrange** [comment]
You need to put `and` or `or` between queries, depending on if you wish to include data matching both queries or either query. For example:

`/ipv6/dhcp-server/binding/print detail where prefix-pool=PoolPD and last-seen<6m`

Furthermore, you need to remove the spaces before `/`, it's not going to work.
