### ISSUE TITLE
Unknown Parameter when using find into brackets

### ISSUE THREAD

**Issue by null31** [GideonLeGrange/mikrotik-java#47]
Hi.
I am having problems when i use the brackets as parameter for remove and editing users of user-manager in ROS.

Versions: ROS 6.38.1 x86, mikrotik-java 3.0.3 jar file, Oracle JDK 8u101

I made some tests with commands below:
conn.execute("/tool/user-manager/user disable [/tool/user-manager/user/find username=ggg]");
conn.execute("/tool/user-manager/user disable [/tool user-manager user find username=ggg]");
conn.execute("/tool/user-manager/user disable [/tool/user-manager/user/find/username=ggg]");

Returns: me.legrange.mikrotik.MikrotikApiException: unknown parameter
Executing into SSH or cli in the ROS was not found problems and works fine (/tool user-manager user disable [/tool user-manager user find username=ggg]).

I ask, has a correct syntax to use brackets with this API? Or simply not works due limitations? Or should i use SSH for this?

Thanks for the helping!

**Comment by tcraib** [comment]
The **find** command is **not** supported on the mikrotik API. See: [API command notes](http://wiki.mikrotik.com/wiki/API_command_notes#Scripting_and_API)
You would need to use:
`conn.execute("/tool/user-manager/user disable where .id=[/tool/user-manager/user/print where username=ggg return .id]`

Or run in 2 executes and get the .id from the first execute

**Comment by GideonLeGrange** [comment]
Thanks @tcraib for responding.

**Comment by null31** [comment]
Hum, thanks for the reply and suggestion! @tcraib
