### ISSUE TITLE
unknown paramater when adding variable into command

### ISSUE THREAD

**Issue by laksamanachenggo** [GideonLeGrange/mikrotik-java#49]
Hi, 
i'm having problem when adding variable into command.
this is command that  i've trouble with:
con.execute("/interface/ppp-client/add add-default-route=no apn="+interface_Apn1+" dial-on-demand=no use-peer-dns=no disabled=no add-default-route=no keepalive-timeout=0 name="+interface_PPP_Out1+" data-channel="+interface_dChannel1+" info-channel="+interface_iChannel1+" phone="+interface_dNumber1+" port=usb1");

i've added "+" (plus) sign between variable, but i keep getting this error me.legrange.mikrotik.MikrotikApiException: unknown parameter.

Thanks for helping.

**Comment by GideonLeGrange** [comment]
Hi 

The first thing I see is that you repeat "add-default-route=no”. I suggest you fix that first and try again. 

Gideon

**Comment by laksamanachenggo** [comment]
Tks Gideon. it work.
