### ISSUE TITLE
Unset Command not working

### ISSUE THREAD

**Issue by etiennesw** [GideonLeGrange/mikrotik-java#50]
Hi All,

I am trying to remove the time schedule from a firewall filter.

This can be easily done in the terminal with the following command:
`/ip/firewall/filter/unset number=4 time`
This removes the time schedule for rule number 4.

Using the API, I tried following the same command format, using the .id instead of number:
`ip/firewall/filter/unset .id=*9 time`

However, it keeps failing. I do not want to remove the entire firewall rule, just the time schedule.
Is there a different way to achieve this from the API?

Thanks

Rgs
Etienne

**Comment by GideonLeGrange** [comment]
Does the API throw an exception, and if so, can you show me the stack trace?

Gideon

**Comment by etiennesw** [comment]
Just managed to solve it last night.

Was going through the PHP API forum and someone quoted a command with "value-name" parameter for unset functionality.

I tried it on the JAVA API and it worked.

Therefore, the command must be as follows:

`/ip/firewall/filter/unset .id=*9 value-name=time`

Thanks for replying.

Rgs
Etienne

**Comment by GideonLeGrange** [comment]
Thanks. This is interesting. 

The use of .id is partially documented, but I've not seen value-name before. I'll look into that, maybe I should improve my own documentation at least. 

Gideon
