### ISSUE TITLE
/queue simple remove

### ISSUE THREAD

**Issue by nikvs84** [GideonLeGrange/mikrotik-java#56]
How to execute command **/queue/simple/remove [/queue/simple/find comment={comment}]** with java API?
As a result of executing the command, I get an exception:
```
me.legrange.mikrotik.impl.ApiCommandException: unknown parameter
	at me.legrange.mikrotik.impl.ApiConnectionImpl$Processor.run(ApiConnectionImpl.java:263)
```

**Comment by ambroseahurra** [comment]
You could try 
`List<Map<String, String> id = con.execute("/queue/simple/print where comment=xx return .id");`
Then use the id to delete;
`con.execute("/queue/simple/remove .id="+id.get(0).get(".id")+"");`
Havent had any luck with using find over the API

**Comment by GideonLeGrange** [comment]
You can't use ```[/[/queue/simple/find ...]``` because you're effectively scripting which is not supported by the underlying API (limitation for RouterOS, not the Java library).

**Comment by nikvs84** [comment]
@ambroseahurra, @GideonLeGrange, thanks!

**Comment by BudFox80** [comment]
Thank U so mutch @ambroseahurra
