### ISSUE TITLE
SSL  connection is slow

### ISSUE THREAD

**Issue by ambroseahurra** [GideonLeGrange/mikrotik-java#57]
Hi Gideon,
I have moved my app to using tls using a 4096 key generated using openssl on my linux machine. however the app has become considerably slower  more  than 6-8 seconds slower ...
any suggestions ..i thought of expected since there is more overhead.
Also this might be my code thats misbehaving but i get random command timeouts, i am using one instance of the ssl connection to do short commands using async task and runnables/threads.
I make a ssl connection once on app lunch then keep using Config.con to execute queries.

```java private Context mcontext;
    private SocketFactory ssl;
    public static ApiConnection con;
    public Config(Context mcontext){
        this.mcontext=mcontext;
        try {
            ssl = ssl();
            con = connect();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    protected SocketFactory ssl() throws Exception{
        // Load CAs from an InputStream
        CertificateFactory cf = CertificateFactory.getInstance("X.509");
        //local cert
        InputStream caInput = new BufferedInputStream(mcontext.getAssets().open("router.crt"));
        Certificate ca1;
        try {
            ca1 = cf.generateCertificate(caInput);
        } finally {
            caInput.close();
        }

        // Create a KeyStore containing our trusted CAs
        String keyStoreType = KeyStore.getDefaultType();
        KeyStore keyStore = KeyStore.getInstance(keyStoreType);
        keyStore.load(null, null);
        keyStore.setCertificateEntry("ca1", ca1);

        // Create a TrustManager that trusts the CAs in our KeyStore
        String tmfAlgorithm = TrustManagerFactory.getDefaultAlgorithm();
        TrustManagerFactory tmf = TrustManagerFactory.getInstance(tmfAlgorithm);
        tmf.init(keyStore);

        // Create an SSLContext that uses our TrustManager
        SSLContext context = SSLContext.getInstance("TLS");
        context.init(null, tmf.getTrustManagers(), null);


        return new TLSFact(context);
    }

    protected  ApiConnection connect() throws Exception {
        ApiConnection con = ApiConnection.connect(ssl, HOST, ApiConnection.DEFAULT_TLS_PORT, ApiConnection.DEFAULT_CONNECTION_TIMEOUT);
        con.login(USERNAME, PASSWORD);
        return con;
    }
```

**Comment by ambroseahurra** [comment]
This seems to be the error causing the timeouts 

`08-05 17:11:22.971 24478-24972/com.megatron.testapp3 E/AndroidRuntime: FATAL EXCEPTION: Mikrotik API Result Processor
    Process: com.megatron.testapp3, PID: 24478
     java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:915)
        at me.legrange.mikrotik.impl.ApiConnectionImpl$Processor.run(ApiConnectionImpl.java:251)`

**Comment by rcpangeran** [comment]
Hi ambroseahurra , mind to share how you can successfully connect to router using SSL? i have tried many things but not yet succeed. 

I use self-signed certificate generated from mikrotik, when trying to use it for https port 443, yes it works. But when apply it to api-ssl , it returns error while doing login , the message is "Connection or outbound has closed"

For info, i use the code from Gideon.
`ApiConnection.connect(mySSLSocketFactory.getDefault(), Config.HOST, ApiConnection.DEFAULT_TLS_PORT, ApiConnection.DEFAULT_CONNECTION_TIMEOUT);`

Already imported the crt file to cacerts in java security lib. But still the error occurred.

So far i just successfully logged in using AnonymousSocketFactory class.

**Comment by ambroseahurra** [comment]
Hi,
I was sending the certs to the router over SFTP using JSch library. then setting them on the API.
Please lemme how you progress :)

**Comment by rcpangeran** [comment]
Hi.. so far i have good progress developing my app using NetBeans IDE. Almost finish though.

My target is to launch app to Android devices. 
But now, i have difficulties make this library work with Android Studio, it always crash on connection state, can't make it work to login method.

Can you help me to solve this problem?
For info, i just tried to connect using non SSL connection, but no luck so far.

**Comment by adsonmanjer** [comment]
> Hi.. so far i have good progress developing my app using NetBeans IDE. Almost finish though.
> 
> My target is to launch app to Android devices. But now, i have difficulties make this library work with Android Studio, it always crash on connection state, can't make it work to login method.
> 
> Can you help me to solve this problem? For info, i just tried to connect using non SSL connection, but no luck so far.

hello sir
can you help me to use this lib to connect using ssl i cant do that with this code only in another apps i can wothout any problem
thanks alot
