### ISSUE TITLE
use netty by this code

### ISSUE THREAD

**Issue by almoulki** [GideonLeGrange/mikrotik-java#58]
hallo , what need i nodify  in this code  for netty use  
and can I use this code in eclipse

**Comment by GideonLeGrange** [comment]
It is Java code structured as a Maven project. Eclipse should be able to import the project.

**Comment by almoulki** [comment]
thank you , but I need netty in this code . how can I netty in this code ??

**Comment by GideonLeGrange** [comment]
I don't know. It is beyond the scope of this project. The code is open source, clone the code and try to do it yourself.
