### ISSUE TITLE
RouterOS 6.43 authentization

### ISSUE THREAD

**Issue by dangelcz** [GideonLeGrange/mikrotik-java#59]
Hi,
I'd like to ask, whether is api prepared for new authentication process which comes with new version 6.43
https://mikrotik.com/download/changelogs
https://wiki.mikrotik.com/wiki/Manual:API#Initial_login

Thanks for reply :-)
D.

**Comment by pafflootiy** [comment]
Please forgive for persistence. Is there any progress?

**Comment by GideonLeGrange** [comment]
Resolved. Use 3.0.5 going forward.
