### ISSUE TITLE
how to change frequency over API?

### ISSUE THREAD

**Issue by aydogankaragoz** [GideonLeGrange/mikrotik-java#62]
Hi, 

I can run following code on terminal successfully,

`/interface wireless set wlan1 frequency=2412`

but when I try to run over API, with the following code: 
`ApiConnection con = ApiConnection.connect("192.168.88.1"); // connect to router`
`con.login("admin",""); // log in to router`
`con.execute("/interface wireless set wlan1 frequency=2457"); // execute a command`
`con.close(); // disconnect from router`
it gives me the following error:
`me.legrange.mikrotik.impl.ParseException: Expected [TEXT] but found EOL at position 27`

How can change frequency via API? 

Cheers,

**Comment by GideonLeGrange** [comment]
Not an API issue, did not read documentation.
