### ISSUE TITLE
Failure on login with empty pass

### ISSUE THREAD

**Issue by Giachelli** [GideonLeGrange/mikrotik-java#65]
Please take a look at login methods.
It respond "Expected [TEXT] but found EOL at position 27" when I try to do:
ApiConnection con = ApiConnection.connect(<IP>);
con.login("admin", "");

--> my credentials of mikrotik are "admin" and no password.

**Comment by etiennesw** [comment]
Hi,

I am still having this problem.

I am implementing 'me.legrange:mikrotik:3.0.5' in my gradle file, however, it seems fixes #65 and '66 are not implemented.

When I attempt to login with a blank passwords I get the EOL at position 27 error.

Can anyone help me on how to get this to work as I am not too familiar with Github.

Thanks in advance.

Rgs
ETienne
