### ISSUE TITLE
Login fails if the password contains ! (Token.PIPE)

### ISSUE THREAD

**Issue by BalleClorin** [GideonLeGrange/mikrotik-java#68]
When parsing the password parameter the parser encounters the ! character and treat the characters up to the ! as the password.

**Comment by vadsh** [comment]
I have the same issue. Is there any workaround?

**Comment by GideonLeGrange** [comment]
This should be fixed by [this change](https://github.com/GideonLeGrange/mikrotik-java/pull/67). You can pull master to test. I have not tested this yet, but when tested I'll release next minor version.
