### ISSUE TITLE
How to implement Pull Request #67 in Android

### ISSUE THREAD

**Issue by etiennesw** [GideonLeGrange/mikrotik-java#74]
Hi,

I am having trouble with the new login on routers v6.45.1 + using Android Studio.

I have downloaded the Java 3.0.5 jar files into my external lib folder and implemented them as dependencies in my gradle file.

Also importing 

```
me.legrande.mikrotik.ApiConnection;
me.legrande.mikrotik.MikrotikApiException;
```

in the Main Activity.

However, when I try to login with no password, I get the following error:

`Mikrotik-java Expected TEXT but found EOl at position 27`

I know this ha been fixed with pull request #67, but I don't know how to implement this in my project?

Any help would be appreciated as I am not famliar with Guthub.

Thanks

Rgs
Etienne

**Comment by GideonLeGrange** [comment]
Hi Etienne 

I should have made a new release after fixing #67 

I have made one now, [v3.0.6](https://github.com/GideonLeGrange/mikrotik-java/releases/tag/v3.0.6) and you can download and use that jar file. 

Gideon

**Comment by etiennesw** [comment]
Hi Gideon,

I confirm it works with v3.0.6

Thank you for your support.

Rgs
Etienne
