### ISSUE TITLE
issue with reading single file from mikrotik router

### ISSUE THREAD

**Issue by ashishonmobile** [GideonLeGrange/mikrotik-java#76]
Hi I am using below command to read a single file from the router.

conn.execute("/file/print\n=.proplist=contents\n?name=test.txt")

But it is not returning me the content of the file. I do not know why \n is not working in this condition.

Do you have any idea why?

Thanks and Regards,
Ashish

**Comment by GideonLeGrange** [comment]
You are not using the API as it was designed to be used. 

Look the the examples in the README and also at this example: [DownloadConfig](https://github.com/GideonLeGrange/mikrotik-java/blob/master/src/main/java/examples/DownloadConfig.java)
