### ISSUE TITLE
query with ~ symbol

### ISSUE THREAD

**Issue by marcosbis** [GideonLeGrange/mikrotik-java#77]
I know the is not currently supported in Mikrotik API but are you aware of any workaound? 
Thanks

**Comment by GideonLeGrange** [comment]
I don't know of a workaround. 

This project implements a wrapper around this API: [https://wiki.mikrotik.com/wiki/Manual:API](https://wiki.mikrotik.com/wiki/Manual:API) and I can only do what they allow.
