### ISSUE TITLE
[Request] Add Tilde in Scanner.java

### ISSUE THREAD

**Issue by federicogualdi** [GideonLeGrange/mikrotik-java#79]
Hi Gideon,
I'm writing to ask if is it possibible to introduce 'Tilde ~' in Scanner.java class

Thank you

**Comment by GideonLeGrange** [comment]
It won't work. If I add it to the scanner it will just fail elsewhere. 

The reason for this is that the RouterOS API on the Mikrotik device itself does not support regular expressions. 

See [API](https://wiki.mikrotik.com/wiki/Manual:API) - there is a bit that reads `Warning: Regular expressions are not supported in API, so do not try to send query with ~ symbol`
