### ISSUE TITLE
New login method of Router OS 

### ISSUE THREAD

**Issue by lluuuo** [GideonLeGrange/mikrotik-java#81]
After Router OS V6.43(maybe),the login command becomes
`/login name =${userName} password =${password}` the login method needs to be modified to be compatible with this

**Comment by GideonLeGrange** [comment]
I think this was fixed in version 3.0.5 

https://github.com/GideonLeGrange/mikrotik-java/issues/59

Can you please try version 3.0.5 and let me know if you still experience a problem. 

Gideon
