### ISSUE TITLE
Thanks gideon

### ISSUE THREAD

**Issue by iyadseizer** [GideonLeGrange/mikrotik-java#82]
I develop your library 
 `implementations 'sy.iyad:mikrotik:1.11.3.0'`
![Screenshot_٢٠٢١-٠٥-١٦-٠٤-٤٢-١٧-٧٧٤_sy e serverconn](https://user-images.githubusercontent.com/40076723/118383116-ddf65e80-b603-11eb-95ba-07d60ffef0a1.jpg)
![Screenshot_٢٠٢١-٠٥-١٦-٠٤-٤٢-٣١-٦٨٨_sy e serverconn](https://user-images.githubusercontent.com/40076723/118383120-e2227c00-b603-11eb-8f09-9746e0f3f0c0.jpg)

**Comment by GideonLeGrange** [comment]
Thank you for letting me know @iyadseizer
